require 'flexible_accessibility/controller_methods.rb'
require 'flexible_accessibility/exceptions.rb'
require 'flexible_accessibility/permission.rb'
require 'flexible_accessibility/filters.rb'
require 'flexible_accessibility/utils.rb'